name: PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX Compile - Schlussbericht
        uses: xu-cheng/latex-action@1.2.1
        with:
          working_directory: ./
          root_file: ipa_jsc_ose_2021.tex
      - uses: actions/upload-artifact@v1
        with:
          name: ipa_jsc_ose_2021
          path: ipa_jsc_ose_2021.pdf
